### PR TITLE
update bandshapes in DB

### PR DESCRIPTION
**Pull request by silviacaprioli**
I have updated the bandshapes for all polarimeters.
Currently, bandshapes are calculated just from one RF test (only one phase-switch state).
With this commit, the bandshape in the DB will be the median between the two RF tests.
I have also added the error on the bandshape.

### CODE REVIEW

**Comment by ziotom78** [comment]
Thanks, Silvia. Might you please fix the build so that Travis works? It seems you forgot to update `Base.show` to take into account the presence of multiple tests in `BandshapeInfo`.

**Comment by silviacaprioli** [comment]
> Thanks, Silvia. Might you please fix the build so that Travis works? It seems you forgot to update Base.show to take into account the presence of multiple tests in BandshapeInfo.

now it should be fine!

**Comment by ziotom78** [comment]
Excellent! I have however another request. The bandshapes look good, but I think that, from now on, we should consider *positive* bandshapes. It's true that the measured bandshapes in Bicocca were measured using negative gains, but it is customary to use *positive* values.

Now that we are going to collaborate with Swipe, I think we should measure bandshapes using *positive* numbers. It's just a matter of switching the signs in the numbers under `bandshape`, so that bands turn from this:

Figure_1

to this:

Figure_2

I think that this would help people in using the database. (I know it's just a sign flip, but if we keep negative numbers I fear we are going to explain over and over again why we have done this.) Is this sign flip quick to do?

**Comment by silviacaprioli** [comment]
Done. You are right, it is something that we should have done sooner or later.
And yes,  it was very quick.
I just  did 
```
  band = database[i]["bandpass"]["bandshape"]
  band_new = [abs(x) for x in band]
```
for each bandshape in the database.

**Pull request merged**
